export const REQUEST_IMAGES = "REQUEST_IMAGES";
export const REQUEST_IMAGE_WITH_COMMENTS = "REQUEST_IMAGE_WITH_COMMENTS";
export const SET_IMAGES = "SET_IMAGES";

export const OPEN_MODAL = "OPEN_MODAL";
export const SET_MODAL = "SET_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SHOW_GALARY_LOADER = "SHOW_GALARY_LOADER";
export const HIDE_GALARY_LOADER = "HIDE_GALARY_LOADER";
export const SHOW_MODAL_LOADER = "SHOW_MODAL_LOADER";
export const HIDE_MODAL_LOADER = "HIDE_MODAL_LOADER";
